sudo: required
services:
    - docker

before_install:
    - docker build -t rizwan/docker-react -f Dockerfile.dev . 

script:
    - docker run rizwan/docker-react npm run test -- --coverage
    
    
